### PR TITLE
refactored into maven project

### PR DESCRIPTION
**Pull request by niels1voo**

### CODE REVIEW

**Comment by hughperkins** [comment]
Well... I dont have a habit of using maven, though perhaps I should.  ant has the advantage of being lightweight.  Some way of making it work with both ant and maven?

**Comment by niels1voo** [comment]
Ivy will let you publish to maven and keep the ant build. Where I work, for some people it's grounds for disqualification if your project is not in a public maven repo.  I could also do gradle.  Let me know.
In the meantime I added newline support.

**Comment by hughperkins** [comment]
Googled a bit, eg http://stackoverflow.com/questions/1163173/why-use-gradle-instead-of-ant-or-maven has some interesting observations.  Gradle sounds interesting to me.  How would this build look in Gradle?

**Comment by niels1voo** [comment]
i made branches for maven, gradle, and easyant with minimal setups.

**Comment by hughperkins** [comment]
- Cloned the 'gradle' branch, installed gradle, (`sudo apt-get install -y gradle`), and then typed `gradle`.  Result was http://pastebin.com/J9cWAXN4 . 
- seems like it has a dependency on maven?  Possible to remove any maven dependency?

**Pull request closed without merging**
